version: '3.7'
secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

services:
  web:
    restart: always
    build:
      context: ./web  # Path to the directory containing your Dockerfile
      dockerfile: Dockerfile.dev  # Specify the Dockerfile to use
    image: pico/official:latest
    container_name: handrehab_web_dev
    volumes:
      - E:/Develop/HandRehabilitation/web:/home/  
    links:
      - postgres:postgres
    secrets:
      - postgres_user
      - postgres_password
    environment:
      DEBUG: False
      POSTGRES_DB: db_dev
      DATABASE_PORT: 5432
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    expose:
      - "4040"
    command: ["bash"]
    stdin_open: true
    tty: true
    depends_on:
      - postgres
  postgres:
    restart: always
    image: postgres:latest
    container_name: handrehab_postgres_dev
    volumes:
      -  db-data-dev:/var/lib/postgresql
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_DB: db_dev
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    ports:
      - "5432:5432"
    expose:
      - "5432"
  redis:
    image: "redis:latest"
  celery_worker:
    build:
      context: ./web  # Path to the directory containing your Dockerfile
      dockerfile: Dockerfile.BackgroundTask.dev  # Specify the Dockerfile to use
    depends_on:
      - redis
      - postgres
    links:
      - redis:redis
      - postgres:postgres 
    secrets:
      - postgres_user
      - postgres_password
    environment:
      DEBUG: False
      POSTGRES_DB: db_dev
      DATABASE_PORT: 5432
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    command: ["bash"]
    stdin_open: true
    tty: true


volumes:
  db-data-dev: