version: '3.7'

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

services:
  nginx:
    restart: always
    image: picomedtech/nginx_prod_otel:v1.1
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/app/static:/app/static
      - ./web/app/static/pdf_files:/app/static/pdf_files:delegated
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    links:
      - web:web
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/html
    entrypoint: "/bin/sh -c 'while true; do certbot renew; sleep 12h; done'"

  web:
    restart: always
    image: picomedtech/official_prod:v1.2
    links:
      - postgres_prod:postgres
    secrets:
      - postgres_user
      - postgres_password
    environment:
      DEBUG: False
      POSTGRES_DB: db
      DATABASE_PORT: 5432
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    # ports:
    #   - "4050:4050"
    expose:
      - "4050"
    # ports:
    #   - "4050:4050"
    depends_on:
      - postgres_prod
    #   sh -c "gunicorn -w 2 -b :4050 app:my_app"
    #   sh -c "flask db upgrade && gunicorn -w 2 -b :8000 app:my_app"
    volumes:
      - ./web/app/static/pdf_files:/app/static/pdf_files:delegated
      - ./web/app:/app/ #Questo volume serve per scaricare direttamente il codice sorgente in produzione
      - ./web/migrations:/migrations/ #Questo volume aggiorna il db in produzione
    # command: ["bash"]
    # stdin_open: true
    # tty: true
    # command: >
    #   sh -c "gunicorn -w 2 -b :4050 app:my_app"
    #   sh -c "flask db upgrade && gunicorn -w 2 -b :8000 app:my_app"

  postgres_prod:
    restart: always
    image: postgres:17.2-alpine3.21
    volumes:
      - /home/db/data:/var/lib/postgresql/data
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_DB: db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    expose:
      - "5432"

volumes:
  db-data:
