version: '3.7'

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

services:
  # nginx:
  #   restart: always
  #   build: ./nginx
  #   ports:
  #     - "4050:4050"
  #   volumes:
  #     - ./web/static:/static
  #   links:
  #     - web:web

  web:
    restart: always
    build: ./web
    image: pico/official_prod:v1.0
    links:
      - postgres:postgres
    secrets:
      - postgres_user
      - postgres_password
    environment:
      DEBUG: False
      POSTGRES_DB: db
      DATABASE_PORT: 5432
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    # ports:
    #   - "4050:4050"
    expose:
      - "4050"
    ports:
      - "4050:4050"
    depends_on:
      - postgres
    # command: ["bash"]
    # stdin_open: true
    # tty: true
    # command: >
    #   sh -c "gunicorn -w 2 -b :4050 app:my_app"
    #   sh -c "flask db upgrade && gunicorn -w 2 -b :8000 app:my_app"

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_DB: db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    expose:
      - "5432"
    ports:
      - "5432:5432"

volumes:
  db-data: