"""aggiornamento data di nascita per il paziente

Revision ID: 4f12fb02e8cd
Revises: b8d93aaa353d
Create Date: 2025-01-07 14:57:57.995976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f12fb02e8cd'
down_revision = 'b8d93aaa353d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
