"""aggiunto campo user mano dominante

Revision ID: 96749d7abfd4
Revises: 328a999e0336
Create Date: 2024-12-27 14:57:19.033634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96749d7abfd4'
down_revision = '328a999e0336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sx_dx_hand', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sx_dx_hand')

    # ### end Alembic commands ###
