"""aggiornamento campi utente

Revision ID: 9d810907c615
Revises: 4f12fb02e8cd
Create Date: 2025-02-08 18:12:26.170737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d810907c615'
down_revision = '4f12fb02e8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_job', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('job', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.alter_column('sx_dx_hand',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('sx_dx_hand',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.drop_column('note')
        batch_op.drop_column('job')
        batch_op.drop_column('manual_job')

    # ### end Alembic commands ###
