FROM python:3.10

COPY requirements.txt requirements.txt

RUN python -m pip install --upgrade pip && python -m pip install -r requirements.txt

#Used to retireve models for sqlAlchemy
COPY background_task /background_task/

COPY app/ /background_task/app/

WORKDIR /background_task